### ISSUE TITLE
NFT's name

### ISSUE THREAD

**Issue by heisenweb** [dabit3/polygon-ethereum-nextjs-marketplace#31]
hey guys, I have a question, base on the NFT contract file, when we create a NFT its name would be "Metaverse". isn't wrong? this way all the NFTs would have the same name. should we choose a different name for each NFT?

**Comment by latonet** [comment]
I think you can just change the name ....

**Comment by slawton3** [comment]
It's a form so when you pick the name when you want to mint the token.  On the create-item.js page you set the name, description, price and image in the createMarket() function.

**Comment by heisenweb** [comment]
> It's a form so you pick the name when you want to mint the token.  On the create-item.js page you set the name, description, price and image in the createMarket() function.  

Hi thank you for answering. I know i can pick a name i just wanna know which way is the right one.

My question is in the Nft.sol file we set  a static name (metaverse i guess).

I mean shouldn't we have something  like a contact that each time an user create a new NFT it deploy a new NFT contract on the chain and mint a new token with the name that user entered?

Somthing like factory pattern.

Or maybe i just misunderstood the concepts.
