### ISSUE TITLE
Create Item page disfunction

### ISSUE THREAD

**Issue by WillStansill** [dabit3/polygon-ethereum-nextjs-marketplace#44]
I've made my way through the majority of the project but for some reason with my create item js file. Even though I am fairly certain my code is spot on, its as if that the create-item page was never made in the first place. Upon deploying the local host I am met with a Home page that runs as intended, but then upon clicking to the sell NFT's tab to make an NFT as he does in the video, I get a simple 404 error
![image](https://user-images.githubusercontent.com/99290776/156480847-b4de3e79-7247-418b-8c9a-4133b5ac6870.png)

![image](https://user-images.githubusercontent.com/99290776/156481258-2660ca3c-2c13-4f68-82b1-5c18c47436c5.png)

Any assistance would be incredibly appreciated.

**Comment by ghost** [comment]
in your page router you are trying to access create-nft but your file is create-item.
Try to change create-nft in router with create-item it might work.

**Comment by WillStansill** [comment]
Thanks so much it ended up working.
