### ISSUE TITLE
Rinkeby support

### ISSUE THREAD

**Issue by bigint** [dabit3/polygon-ethereum-nextjs-marketplace#5]
It would be great if rinkeby is supported when switched to rinkeby I'm getting this error 🤔 

![image](https://user-images.githubusercontent.com/69431456/135991347-be670a3e-ae74-43c1-af5d-40bd44f23b4b.png)

/cc @dabit3

**Comment by Haidar1528** [comment]
change the web3 modal mumbai to rinkeby after adding rinkeby in hardhat.config.js

**Comment by bigint** [comment]
It works thanks!

**Comment by kyokosdream** [comment]
Can you please be specific about where to make this change? I have the rinkeby network setup in hardhat.config.js with my Infura rinkeby url and MetaMask wallet private key.
