### ISSUE TITLE
Error uploading file

### ISSUE THREAD

**Issue by skyairmj** [dabit3/polygon-ethereum-nextjs-marketplace#50]
Following local setup instruction step by step, the service is up and running.

However, when uploading an image, it prints error message as bellow in chrome console:
![image](https://user-images.githubusercontent.com/130340/161879124-3dbb69ac-d098-4f5e-b679-9eb43d36b4ea.png)

The runtime dependencies are identical with the declarations in yarn.lock.

Would anyone help fix it? Thanks in advance.

**Comment by YuanBoXie** [comment]
See this article: https://blog.csdn.net/qq_33583069/article/details/125513023

**Comment by skyairmj** [comment]
@hexbo thanks, it works.
