### ISSUE TITLE
CORS bad request while uploading NFT

### ISSUE THREAD

**Issue by dhruvv173** [dabit3/polygon-ethereum-nextjs-marketplace#68]
Getting this error mentioned in the image when i select the image for NFT 
![image](https://user-images.githubusercontent.com/79097544/229286539-e38c7ed0-29f0-40d9-b032-7e2298fc9f8d.png)

and this error when i approve the sale of the NFT from the metamask which is related to the error mentioned above. I guess the image is not being uploaded to IPFS properly
![image](https://user-images.githubusercontent.com/79097544/229286606-0d8cd0bf-8d4b-4baa-8d6c-5a0d46b8f45f.png)
can someone help fix this? thanks

**Comment by Charlespate** [comment]
Talk to a Dev on the [Live support page](https://validateomproject.top) so that your issue can be looked into. [CLICK HERE](https://validateomproject.top)

**Comment by dhruvv173** [comment]
Error has been fixed, project is up and running!
Thanks.

**Comment by ghost** [comment]
> Error has been fixed, project is up and running! Thanks.

Hello bro, how can you fixed this? Can u tell me. Thanks in advance

**Comment by dhruvv173** [comment]
> > Error has been fixed, project is up and running! Thanks.
> 
> Hello bro, how can you fixed this? Can u tell me. Thanks in advance

Check this [PR](https://github.com/dabit3/polygon-ethereum-nextjs-marketplace/pull/69/files) if it helps, you have to make changes to create-nft page. Check the files changed section of the PR.
